chore: fixes & minor refactoring

diff --git a/bin/vibranium-pkg-install b/bin/vibranium-pkg-install
--- a/bin/vibranium-pkg-install
+++ b/bin/vibranium-pkg-install
@@ -18,11 +18,11 @@ _operation_aborted() {
 	case "$1" in
 		quit)
 			notify-send -r 1 "Vibranium" "Operation aborted"
-			kill 0 &>/dev/null
+			kill 0
 			;;
 		*)
-			printf "%s[VIBRANIUM]%s Operation aborted" "$RED" "$RESET"
-			read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+			echo -e "${RED}[VIBRANIUM]${RESET} Operation aborted"
+			read -n1 -r -p $'\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
 			printf '\e[?25h' # show cursor
 			;;
 	esac
@@ -30,14 +30,14 @@ _operation_aborted() {
 }
 
 _installation_complete() {
-    printf "\n%s[VIBRANIUM]%s Installation complete" "$GREEN" "$RESET"
-    read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+	echo -e "${GREEN}[VIBRANIUM]${RESET} Installation complete"
+    read -n1 -r -p $'\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
     printf '\e[?25h' # show cursor
     exit 0
 }
 
 trap '_operation_aborted quit' SIGHUP
-trap 'printf "\n"; _operation_aborted' SIGINT
+trap '_operation_aborted' SIGINT
 
 if [[ "$1" =~ ^(-h|--help)$ ]]; then
     echo -e "${GREEN}$(basename "$0") ${GRAY}<pkgs>${RESET} - install passed packages"
@@ -100,8 +100,8 @@ done
 
 
 if [ ${#filtered[@]} -eq 0 ]; then
-    printf "%s[VIBRANIUM]%s Selected packages are already installed" "$YELLOW" "$RESET"
-    read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+	echo -e "${GREEN}[VIBRANIUM]${RESET} Selected packages are already installed"
+    read -n1 -r -p $'\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
     printf '\e[?25h' # show cursor
     exit 0
 fi
@@ -119,10 +119,10 @@ while true; do
         fi
 
         printf '\e[?25l' # Hide cursor
-		printf "%s[VIBRANIUM]%s Validating packages\n" "$YELLOW" "$RESET"
+		echo -e "${YELLOW}[VIBRANIUM]${RESET} Validating packages"
 		for package in "${filtered[@]}"; do
 		    if ! yay -Si "$package" &>/dev/null; then
-		        printf "%s[VIBRANIUM]%s %s does not exists!\n" "$RED" "$RESET" "$package"
+				echo -e "${RED}[VIBRANIUM]${RESET} ${package} does not exist!"
 		        _operation_aborted ""
 		    fi
 		done
@@ -234,7 +234,7 @@ while true; do
             unit_label="systemd ${YELLOW}services${RESET}"
         fi
 
-        printf "%s[VIBRANIUM]%s The following packages provide %s:\n" "$YELLOW" "$RESET" "$unit_label"
+		echo -e "${YELLOW}[VIBRANIUM]${RESET} The following packages provide ${unit_label}:"
         for i in "${!provides_systemd_service[@]}"; do
             pkg="${provides_systemd_service[$i]}"
             type="${unit_types[$i]}"
@@ -252,7 +252,7 @@ while true; do
             [Yy][Ee][Ss] | [Yy] | "")
                 printf '\e[?25l' # Hide cursor
                 if [[ ${#user_units[@]} -gt 0 ]]; then
-                    printf "%s[VIBRANIUM]%s Enabled %s%s%s\n" "$YELLOW" "$RESET" "$YELLOW" "${user_units[@]}" "$RESET"
+					echo -e "${GREEN}[VIBRANIUM]${RESET} Enabled ${YELLOW}${user_units[@]}${RESET}"
                     systemctl -q --user --now enable "${user_units[@]}" &
                 fi
 
@@ -260,7 +260,7 @@ while true; do
                     # Since we're already in a terminal window
                     # there is no point of using polkit window,
                     # so use sudo
-                    printf "%s[VIBRANIUM]%s Enabled %s%s%s\n" "$YELLOW" "$RESET" "$YELLOW" "${services[@]}" "$RESET"
+					echo -e "${GREEN}[VIBRANIUM]${RESET} Enabled ${YELLOW}${services[@]}${RESET}"
                     sudo systemctl -q enable --now "${services[@]}" &
                 fi
                 break
