refactor!(project): refactor entire project through shfmt

diff --git a/bin/vibranium-cmd-system-update b/bin/vibranium-cmd-system-update
--- a/bin/vibranium-cmd-system-update
+++ b/bin/vibranium-cmd-system-update
@@ -4,41 +4,42 @@
 
 source "$VIBRANIUM_PATH/vibranium-core-lib"
 
-export SUDO_PROMPT; SUDO_PROMPT="$(printf '%s[VIBRANIUM]%s Password for %s: ' "$RED" "$RESET" "$USER")"
+export SUDO_PROMPT
+                    SUDO_PROMPT="$(printf '%s[VIBRANIUM]%s Password for %s: ' "$RED" "$RESET" "$USER")"
 
 if ! tty -s; then
-	exec setsid vibranium-cmd-launch-terminal "$0" "$@"
-	exit 0
+    exec setsid vibranium-cmd-launch-terminal "$0" "$@"
+    exit 0
 fi
 
 printf "\n\e[33m%s\e[0m\n\n" "$(cat "$VIBRANIUM/logo.txt")"
 
 if ! sudo -v; then
-	echo -e "${RED}[VIBRANIUM]${RESET} Operation aborted"
-	exit 1
+    echo -e "${RED}[VIBRANIUM]${RESET} Operation aborted"
+    exit 1
 fi
 
 # Hide cursor
 printf '\e[?25l'
 
-yay -Sy &>/dev/null &
+yay -Sy &> /dev/null &
 spinner "$!" "${YELLOW}[VIBRANIUM]${RESET} Refreshing repositories" ""
 
 mapfile -t pkg_list < <(yay -Qqu)
 
 if [[ -z "${pkg_list[*]}" ]]; then
-	echo -e "${GREEN}[VIBRANIUM]${RESET} You are up to date "
-	read -n1 -r -p $'\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
-	exit 0
+    echo -e "${GREEN}[VIBRANIUM]${RESET} You are up to date "
+    read -n1 -r -p $'\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+    exit 0
 fi
 
 echo -e "${YELLOW}[VIBRANIUM]${RESET} ${#pkg_list[@]} packages are awaiting updates"
 echo -e "${YELLOW}[VIBRANIUM]${RESET} Starting system update..."
 
 if ! yay --noconfirm --sudoloop; then
-	echo -e "${RED}[VIBRANIUM]${RESET} Something went wrong"
-	read -n1 -r -p $'\e[0;31m[VIBRANIUM]\e[0m Press any key to close this window' dummy
-	exit 1
+    echo -e "${RED}[VIBRANIUM]${RESET} Something went wrong"
+    read -n1 -r -p $'\e[0;31m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+    exit 1
 fi
 
 vibranium-cmd-refresh-waybar-module pacman
@@ -53,17 +54,17 @@ for pkg in "${pkg_list[@]}"; do
         while :; do
             printf "%s\e[?25h" "$prompt"
             read -r answer
-			printf '\e[?25l'
+            printf '\e[?25l'
             case "$answer" in
-                [Yy][Ee][Ss]|[Yy]|"")
-					printf '\e[?25l'
-					for i in {3..1}; do
-						printf "\r\033[K%s[VIBRANIUM]%s Restarting in %d..." "$YELLOW" "$RESET" "$i"
-						sleep 1
-					done
-					systemctl reboot
+                [Yy][Ee][Ss] | [Yy] | "")
+                    printf '\e[?25l'
+                    for i in {3..1}; do
+                        printf "\r\033[K%s[VIBRANIUM]%s Restarting in %d..." "$YELLOW" "$RESET" "$i"
+                        sleep 1
+                    done
+                    systemctl reboot
                     ;;
-                [Nn][Oo]|[Nn])
+                [Nn][Oo] | [Nn])
                     break
                     ;;
                 *)
diff --git a/bin/vibranium-core-brightness b/bin/vibranium-core-brightness
--- a/bin/vibranium-core-brightness
+++ b/bin/vibranium-core-brightness
@@ -21,8 +21,8 @@ Usage:
 EOF
 }
 
-if pidof ddcutil >/dev/null; then
-	exit 0
+if pidof ddcutil > /dev/null; then
+    exit 0
 fi
 
 if [ -z "$1" ]; then
@@ -36,15 +36,15 @@ fi
 # Yes, I know that this file is created at the start of the session in the startup-functions file.
 # But let's make it more robust.
 if [[ ! -f "$VIBRANIUM_STATE/i2c-bus" ]]; then
-	I2C_BUS="$(ddcutil detect 2> /dev/null | awk -F'i2c-' '/I2C bus/{print $2}')"
+    I2C_BUS="$(ddcutil detect 2> /dev/null | awk -F'i2c-' '/I2C bus/{print $2}')"
 else
-	I2C_BUS="$(<"$VIBRANIUM_STATE/i2c-bus")"
+    I2C_BUS="$(< "$VIBRANIUM_STATE/i2c-bus")"
 fi
 
 if [ -z "$(ls -A /sys/class/backlight)" ]; then
     check_bool VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL false
 
-	# If the driver for adjusting the brightness of the built-in screen is not found and DDC control is disabled globally
+    # If the driver for adjusting the brightness of the built-in screen is not found and DDC control is disabled globally
     if [[ $VIBRANIUM_BRIGHTNESS_USE_DDC_CONTROL == false ]]; then
         error "This feature is disabled in Vibranium settings"
         exit 1
@@ -56,9 +56,9 @@ if [ -z "$(ls -A /sys/class/backlight)" ]; then
         fi
 
         method="DDC"
-		# TODO: As far as I know, optimal values for --sleep-multiplier can vary from monitor to monitor,
-		# and while it works well on one monitor, it may not work at all on another.
-		# In this case, we need to create a mini-algorithm that will calculate and record valid values for the monitor and use them.
+        # TODO: As far as I know, optimal values for --sleep-multiplier can vary from monitor to monitor,
+        # and while it works well on one monitor, it may not work at all on another.
+        # In this case, we need to create a mini-algorithm that will calculate and record valid values for the monitor and use them.
         ddcutil_flags=(--sleep-multiplier 0.13 --noverify --skip-ddc-checks --maxtries 1,1,1)
     fi
 else
@@ -81,7 +81,7 @@ osd() {
     local value="$1"
     local icon progress
 
-	# Set specific icons depending on the current brightness level (icons are taken from the active icon pack)
+    # Set specific icons depending on the current brightness level (icons are taken from the active icon pack)
     if ((value <= 30)); then
         icon="brightness-low-symbolic"
     elif ((value <= 70)); then
@@ -90,11 +90,11 @@ osd() {
         icon="brightness-high-symbolic"
     fi
 
-	# Build a brightness value for SwayOSD
+    # Build a brightness value for SwayOSD
     progress=$(awk -v v="$value" 'BEGIN {p = 0.02 + v * (0.98/100); printf "%.2f", p}')
 
-	# I can't imagine a situation where this service would be turned off, but let it be there just in case
-	[[ ! $(pidof swayosd-server) ]] && systemctl --user enable --now swayosd
+    # I can't imagine a situation where this service would be turned off, but let it be there just in case
+    [[ ! $(pidof swayosd-server) ]] && systemctl --user enable --now swayosd
     swayosd-client --custom-icon="$icon" --custom-progress="$progress" || true
 }
 
@@ -103,47 +103,48 @@ step=$VIBRANIUM_BRIGHTNESS_STEP
 
 case "$method" in
     "DDC")
-		if [[ -f "$VIBRANIUM_STATE/brightness" ]]; then
-			current="$(<"$VIBRANIUM_STATE/brightness")"
-		else
-			# Same as above.
-			# -----------------
-			# As I mentioned above, --sleep-multiplier can sometimes fail at very low values,
-			# so we give the command three attempts to get the date from the monitor using the DDC protocol.
-			retries=3; for ((i = 0; i < retries; i++)); do
-				current=$(ddcutil --bus "$I2C_BUS" "${ddcutil_flags[@]}" getvcp 10 2> /dev/null | awk '/current/ {print int($9)}')
-				if [[ $current =~ ^[0-9]+$ ]] && ((current >= 0 && current <= 100)); then
-					break
-				fi
-			done
-		fi
+        if [[ -f "$VIBRANIUM_STATE/brightness" ]]; then
+            current="$(< "$VIBRANIUM_STATE/brightness")"
+        else
+            # Same as above.
+            # -----------------
+            # As I mentioned above, --sleep-multiplier can sometimes fail at very low values,
+            # so we give the command three attempts to get the date from the monitor using the DDC protocol.
+            retries=3
+              for ((i = 0; i < retries; i++)); do
+                current=$(ddcutil --bus "$I2C_BUS" "${ddcutil_flags[@]}" getvcp 10 2> /dev/null | awk '/current/ {print int($9)}')
+                if [[ $current =~ ^[0-9]+$ ]] && ((current >= 0 && current <= 100)); then
+                    break
+                fi
+            done
+        fi
 
-		# The remaining code at the bottom is generally self-explanatory
+        # The remaining code at the bottom is generally self-explanatory
         case "$1" in
             "up")
-				(( current == 100 )) && exit 0
+                ((current == 100)) && exit 0
                 new=$((current + step))
                 ((new > 100)) && new=100
                 ;;
             "down")
-				(( current == 0 )) && exit 0
+                ((current == 0)) && exit 0
                 new=$((current - step))
                 ((new < 0)) && new=0
                 ;;
             *)
                 if [[ $1 =~ ^[0-9]+$ ]]; then
-					if (( current == 0 && $1 == 0 )); then
-						exit 0
-					elif (( current == 100 && $1 == 100 )); then
-						exit 0
-					fi
+                    if ((current == 0 && $1 == 0)); then
+                        exit 0
+                    elif ((current == 100 && $1 == 100)); then
+                        exit 0
+                    fi
 
-					if (($1 >= 0 && $1 <= 100)); then
-						new=$1
-					else
-						error "Out of boundary"
-						exit 1
-					fi
+                    if (($1 >= 0 && $1 <= 100)); then
+                        new=$1
+                    else
+                        error "Out of boundary"
+                        exit 1
+                    fi
                 else
                     error "Invalid input!"
                     exit 1
@@ -151,16 +152,16 @@ case "$method" in
                 ;;
         esac
 
-		log "Method: ${YELLOW}'""$method""'${RESET}"
-		log "DDC flags: ${YELLOW}'""${ddcutil_flags[*]}""'${RESET}"
-		log "Current brightness: ${YELLOW}'""${current}""'${RESET}"
-		log "New brightness: ${YELLOW}'""$new""'${RESET}"
+        log "Method: ${YELLOW}'""$method""'${RESET}"
+        log "DDC flags: ${YELLOW}'""${ddcutil_flags[*]}""'${RESET}"
+        log "Current brightness: ${YELLOW}'""${current}""'${RESET}"
+        log "New brightness: ${YELLOW}'""$new""'${RESET}"
 
-		# Move the command to the background to show instant OSD / Notification
+        # Move the command to the background to show instant OSD / Notification
         ddcutil --bus "$I2C_BUS" "${ddcutil_flags[@]}" setvcp 10 "$new" &
 
-		# Save state file
-		printf "%s" "$new" > "$VIBRANIUM_STATE/brightness"
+        # Save state file
+        printf "%s" "$new" > "$VIBRANIUM_STATE/brightness"
 
         check_bool VIBRANIUM_BRIGHTNESS_USE_OSD true
         check_bool VIBRANIUM_GLOBAL_USE_OSD true
@@ -171,57 +172,56 @@ case "$method" in
             notify-send -r 2 -t 1000 "Brightness ${new}%" -h int:value:"$new"
         fi
         ;;
-	"brightnessctl")
-		if [ -f "$VIBRANIUM_STATE/brightness" ]; then
-			current="$(<"$VIBRANIUM_STATE/brightness")"
-		else
-			current_raw=$(brightnessctl g 2>/dev/null)
-			max_raw=$(brightnessctl m 2>/dev/null)
-			current=$((current_raw * 100 / max_raw))
-		fi
+    "brightnessctl")
+        if [ -f "$VIBRANIUM_STATE/brightness" ]; then
+            current="$(< "$VIBRANIUM_STATE/brightness")"
+        else
+            current_raw=$(brightnessctl g 2> /dev/null)
+            max_raw=$(brightnessctl m 2> /dev/null)
+            current=$((current_raw * 100 / max_raw))
+        fi
 
-		case "$1" in
-			up)
-				arg="+${step}"
-				new=$(( current + step ))
-				;;
-			down)
-				arg="-${step}"
-				new=$(( current - step ))
-				;;
-			*)
-				if [[ "$1" =~ ^[0-9]+$ && $1 -ge 0 && $1 -le 100 ]]; then
-					arg="$1"
-					new="$arg"
-				else
-					error "Invalid input!"
-					exit 1
-				fi
-				;;
-		esac
+        case "$1" in
+            up)
+                arg="+${step}"
+                new=$((current + step))
+                ;;
+            down)
+                arg="-${step}"
+                new=$((current - step))
+                ;;
+            *)
+                if [[ "$1" =~ ^[0-9]+$ && $1 -ge 0 && $1 -le 100 ]]; then
+                    arg="$1"
+                    new="$arg"
+                else
+                    error "Invalid input!"
+                    exit 1
+                fi
+                ;;
+        esac
 
-		(( new > 100 )) && new=100
-		(( new < 0 )) && new=0
+        ((new > 100)) && new=100
+        ((new < 0)) && new=0
 
-		log "Method: ${YELLOW}'""$method""'${RESET}"
-		log "Current brightness: ${YELLOW}'""${current}""'${RESET}"
-		log "New brightness: ${YELLOW}'""$new""'${RESET}"
+        log "Method: ${YELLOW}'""$method""'${RESET}"
+        log "Current brightness: ${YELLOW}'""${current}""'${RESET}"
+        log "New brightness: ${YELLOW}'""$new""'${RESET}"
 
-		if [[ $VIBRANIUM_GLOBAL_USE_OSD == true && $VIBRANIUM_BRIGHTNESS_USE_OSD == true ]]; then
-			swayosd-client --brightness="$arg"
-		else
-			brightnessctl -q set "${new}%"
-			notify-send -r 1 -t 1000 "Brightness ${new}%" -h int:value:"$new"
-		fi
+        if [[ $VIBRANIUM_GLOBAL_USE_OSD == true && $VIBRANIUM_BRIGHTNESS_USE_OSD == true ]]; then
+            swayosd-client --brightness="$arg"
+        else
+            brightnessctl -q set "${new}%"
+            notify-send -r 1 -t 1000 "Brightness ${new}%" -h int:value:"$new"
+        fi
 
-		printf "%s" "$new" > "$VIBRANIUM_STATE/brightness"
-		;;
+        printf "%s" "$new" > "$VIBRANIUM_STATE/brightness"
+        ;;
 esac
 
 check_bool VIBRANIUM_BAR_BRIGHTNESS_MODULE_ENABLE false
 
 # Update waybar module
 if [[ $VIBRANIUM_BAR_BRIGHTNESS_MODULE_ENABLE == true ]]; then
-	vibranium-cmd-refresh-waybar-module brightness
+    vibranium-cmd-refresh-waybar-module brightness
 fi
-
