feat: package validation & formatting

diff --git a/bin/vibranium-pkg-install b/bin/vibranium-pkg-install
--- a/bin/vibranium-pkg-install
+++ b/bin/vibranium-pkg-install
@@ -10,28 +10,28 @@ SUDO_PROMPT="$(printf '%s[VIBRANIUM]%s Password for %s: ' "$RED" "$RESET" "$USER
 TMPDIR="$XDG_RUNTIME_DIR"
 
 if ! tty -s; then
-	exec setsid vibranium-cmd-launch-terminal "$0" "$@"
-	exit 0
+    exec setsid vibranium-cmd-launch-terminal "$0" "$@"
+    exit 0
 fi
 
 _operation_aborted() {
-	printf "%s[VIBRANIUM]%s Operation aborted" "$RED" "$RESET"
-	read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
-	printf '\e[?25h'  # show cursor
-	exit 1
+    printf "%s[VIBRANIUM]%s Operation aborted" "$RED" "$RESET"
+    read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+    printf '\e[?25h' # show cursor
+    exit 1
 }
 
 _installation_complete() {
-	printf "%s[VIBRANIUM]%s Installation complete" "$YELLOW" "$RESET"
-	read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
-	printf '\e[?25h'  # show cursor
-	exit 0
+    printf "%s[VIBRANIUM]%s Installation complete" "$YELLOW" "$RESET"
+    read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+    printf '\e[?25h' # show cursor
+    exit 0
 }
 
 if [[ "$1" =~ ^(-h|--help)$ ]]; then
-	echo -e "${GREEN}$(basename "$0") ${GRAY}<pkgs>${RESET} - install passed packages"
-	echo -e "${GREEN}$(basename "$0") ${GRAY}${RESET}       - select and install"
-	exit 0
+    echo -e "${GREEN}$(basename "$0") ${GRAY}<pkgs>${RESET} - install passed packages"
+    echo -e "${GREEN}$(basename "$0") ${GRAY}${RESET}       - select and install"
+    exit 0
 fi
 
 printf "\n%s%s\n" "$YELLOW" "$(cat "$VIBRANIUM/logo.txt")" "$RESET"
@@ -51,196 +51,198 @@ fzf_args=(
 )
 
 if [ $# -gt 0 ]; then
-	chosen=()
-	for pkg in "$@"; do
-		if ! pacman -Qq "$pkg" &>/dev/null; then
-			chosen+=("$pkg")
-		fi
-	done
+    chosen=()
+    for pkg in "$@"; do
+        if ! pacman -Qq "$pkg" &>/dev/null; then
+            chosen+=("$pkg")
+        fi
+    done
 else
     arch_file=$(mktemp)
     yay_file=$(mktemp)
 
-    (pacman -Slq > "$arch_file") &
+    (pacman -Slq >"$arch_file") &
     spinner $! "${YELLOW}[VIBRANIUM]${RESET} Fetching Arch packages" ""
-    mapfile -t arch_packages < "$arch_file"
+    mapfile -t arch_packages <"$arch_file"
     total_packages=("${arch_packages[@]}")
 
-    (yay -Slqa > "$yay_file") &> /dev/null &
+    (yay -Slqa >"$yay_file") &>/dev/null &
     spinner $! "${YELLOW}[VIBRANIUM]${RESET} Fetching AUR packages" ""
-    mapfile -t aur_packages < "$yay_file"
+    mapfile -t aur_packages <"$yay_file"
     total_packages+=("${aur_packages[@]}")
 
     rm "$arch_file" "$yay_file"
 
-	mapfile -t chosen < <(printf "%s\n" "${total_packages[@]}" | fzf "${fzf_args[@]}")
+    mapfile -t chosen < <(printf "%s\n" "${total_packages[@]}" | fzf "${fzf_args[@]}")
 
     if [ ${#chosen[@]} -eq 0 ]; then
-		_operation_aborted
+        _operation_aborted
     fi
 fi
 
 filtered=()
 for package in "${chosen[@]}"; do
-    if ! pacman -Qq "$package" &> /dev/null; then
+    if ! pacman -Qq "$package" &>/dev/null; then
         filtered+=("$package")
     fi
 done
 
-for package in "${filtered[@]}"; do
-	if ! pacman -Si "$package" &>/dev/null; then
-		printf "%s[VIBRANIUM]%s %s does not exists!\n" "$RED" "$RESET" "$package"
-		_operation_aborted
-	fi
-done
 
 if [ ${#filtered[@]} -eq 0 ]; then
-	printf "%s[VIBRANIUM]%s Selected packages are already installed" "$YELLOW" "$RESET"
-	read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
-	printf '\e[?25h'  # show cursor
-	exit 0
+    printf "%s[VIBRANIUM]%s Selected packages are already installed" "$YELLOW" "$RESET"
+    read -n1 -r -p $'\n\e[0;33m[VIBRANIUM]\e[0m Press any key to close this window' dummy
+    printf '\e[?25h' # show cursor
+    exit 0
 fi
 
-printf '\e[?25h'  # show cursor
-prompt=$'\e[0;33m[VIBRANIUM]\e[0m You are about to install following packages: \e[0;33m'"${chosen[*]}"$'\e[0m. Proceed? (Y/n): \e[0m'
+printf '\e[?25h' # show cursor
+prompt=$'\e[0;33m[VIBRANIUM]\e[0m You are about to install the following packages: \e[0;33m'"${chosen[*]}"$'\e[0m. Proceed? (Y/n): \e[0m'
 
 while true; do
     printf "%s" "$prompt"
     read -r answer
     case "$answer" in
-        [Yy][Ee][Ss] | [Yy] | "")
-			if ! sudo -v; then
-				_operation_aborted
-			fi
+    [Yy][Ee][Ss] | [Yy] | "")
+        if ! sudo -v; then
+            _operation_aborted
+        fi
 
-            printf '\e[?25l' # Hide cursor
-            yay -S --noconfirm "${filtered[@]}" &> /dev/null &
-            spinner $! "${YELLOW}[VIBRANIUM]${RESET} Installing packages" ""
+		printf "%s[VIBRANIUM]%s Validating selected packages\n" "$YELLOW" "$RESET"
+		for package in "${filtered[@]}"; do
+		    if ! pacman -Si "$package" &>/dev/null; then
+		        printf "%s[VIBRANIUM]%s %s does not exists!\n" "$RED" "$RESET" "$package"
+		        _operation_aborted
+		    fi
+		done
 
-            services=()
-            provides_systemd_service=()
-            user_units=()
-            unit_types=()
+        printf '\e[?25l' # Hide cursor
+        yay -S --noconfirm "${filtered[@]}" &>/dev/null &
+        spinner $! "${YELLOW}[VIBRANIUM]${RESET} Installing packages" ""
 
-            for pkg in "${filtered[@]}"; do
-                units=$(pacman -Ql "$pkg" | awk '/\/systemd\/.*\.(service|socket)$/ && $2 !~ /@/ {print $2}')
-                [[ -z $units ]] && continue
+        services=()
+        provides_systemd_service=()
+        user_units=()
+        unit_types=()
 
-                user_socket= user_service=
-                sys_socket= sys_service=
+        for pkg in "${filtered[@]}"; do
+            units=$(pacman -Ql "$pkg" | awk '/\/systemd\/.*\.(service|socket)$/ && $2 !~ /@/ {print $2}')
+            [[ -z $units ]] && continue
 
-                while read -r unit; do
-                    case "$unit" in
-                        */systemd/user/*.socket)
-                            [[ -z $user_socket ]] && user_socket="$unit"
-                            ;;
-                        */systemd/user/*.service)
-                            [[ -z $user_service ]] && user_service="$unit"
-                            ;;
-                        */systemd/system/*.socket)
-                            [[ -z $sys_socket ]] && sys_socket="$unit"
-                            ;;
-                        */systemd/system/*.service)
-                            [[ -z $sys_service ]] && sys_service="$unit"
-                            ;;
-                    esac
-                done <<< "$units"
+            user_socket= user_service=
+            sys_socket= sys_service=
 
-                if [[ -n $user_socket ]]; then
-                    provides_systemd_service+=("$pkg")
-                    user_units+=("$(basename "$user_socket")")
-                    unit_types+=("socket")
-                    unit_scope+=("user")
-                    continue
-                elif [[ -n $user_service ]]; then
-                    provides_systemd_service+=("$pkg")
-                    user_units+=("$(basename "$user_service")")
-                    unit_types+=("service")
-                    unit_scope+=("user")
-                    continue
-                fi
-
-                if [[ -n $sys_socket ]]; then
-                    provides_systemd_service+=("$pkg")
-                    services+=("$(basename "$sys_socket")")
-                    unit_types+=("socket")
-                    unit_scope+=("system")
-                    continue
-                elif [[ -n $sys_service ]]; then
-                    provides_systemd_service+=("$pkg")
-                    services+=("$(basename "$sys_service")")
-                    unit_types+=("service")
-                    unit_scope+=("system")
-                fi
-            done
-
-            if [[ ${#provides_systemd_service[@]} -eq 0 ]]; then
-                _installation_complete
-            fi
-
-            has_socket=false
-            has_service=false
-            for type in "${unit_types[@]}"; do
-                [[ $type == "socket" ]] && has_socket=true
-                [[ $type == "service" ]] && has_service=true
-            done
-
-            if $has_socket && $has_service; then
-                unit_label="systemd ${YELLOW}services${RESET} and ${YELLOW}sockets${RESET}"
-            elif $has_socket; then
-                unit_label="systemd ${YELLOW}sockets${RESET}"
-            else
-                unit_label="systemd ${YELLOW}services${RESET}"
-            fi
-
-            printf "%s[VIBRANIUM]%s The following packages provide %s:\n" "$YELLOW" "$RESET" "$unit_label"
-            for i in "${!provides_systemd_service[@]}"; do
-                pkg="${provides_systemd_service[$i]}"
-                type="${unit_types[$i]}"
-                scope="${unit_scope[$i]}"
-
-                echo -e "  - ${YELLOW}$pkg${RESET} (${scope} ${type})"
-            done
-
-            prompt2=$'\e[0;33m[VIBRANIUM]\e[0m Do you wish to enable and start them now? (Y/n): '
-            while true; do
-                printf '\e[?25h' # show cursor
-                printf "%s" "$prompt2"
-                read -r answer
-                case "$answer" in
-                    [Yy][Ee][Ss] | [Yy] | "")
-                        printf '\e[?25l' # Hide cursor
-                        if [[ ${#user_units[@]} -gt 0 ]]; then
-							printf "%s[VIBRANIUM]%s Enabled %s%s%s\n" "$YELLOW" "$RESET" "$YELLOW" "${user_units[@]%.*}" "$RESET"
-                            systemctl -q --user --now enable "${user_units[@]}" &
-                        fi
-
-                        if [[ ${#services[@]} -gt 0 ]]; then
-							# Since we're already in a terminal window
-							# there is no point of using polkit window,
-							# so use sudo
-							printf "%s[VIBRANIUM]%s Enabled %s%s%s\n" "$YELLOW" "$RESET" "$YELLOW" "${services[@]}" "$RESET"
-                            sudo systemctl -q enable --now "${services[@]}" &
-                        fi
-                        break
-                        ;;
-                    [Nn][Oo] | [Nn])
-                        printf '\e[?25l' # Hide cursor
-                        break
-                        ;;
-                    *) # Wrong input
-                        printf '\e[A\r\e[K'  # Go up, to start, clear line
-                        ;;
+            while read -r unit; do
+                case "$unit" in
+                */systemd/user/*.socket)
+                    user_socket="$unit"
+                    ;;
+                */systemd/user/*.service)
+                    [[ -z $user_service ]] && user_service="$unit"
+                    ;;
+                */systemd/system/*.socket)
+                    sys_socket="$unit"
+                    ;;
+                */systemd/system/*.service)
+                    [[ -z $sys_service ]] && sys_service="$unit"
+                    ;;
                 esac
-            done
+            done <<<"$units"
 
-			_installation_complete
-            ;;
-        [Nn][Oo] | [Nn])
-			_operation_aborted
-            ;;
-        *) # Wrong input
-            printf '\e[A\r\e[K'  # Go up, to start, clear line
-            ;;
+            if [[ -n $user_socket ]]; then
+                provides_systemd_service+=("$pkg")
+                user_units+=("$(basename "$user_socket")")
+                unit_types+=("socket")
+                unit_scope+=("user")
+                continue
+            elif [[ -n $user_service ]]; then
+                provides_systemd_service+=("$pkg")
+                user_units+=("$(basename "$user_service")")
+                unit_types+=("service")
+                unit_scope+=("user")
+                continue
+            fi
+
+            if [[ -n $sys_socket ]]; then
+                provides_systemd_service+=("$pkg")
+                services+=("$(basename "$sys_socket")")
+                unit_types+=("socket")
+                unit_scope+=("system")
+                continue
+            elif [[ -n $sys_service ]]; then
+                provides_systemd_service+=("$pkg")
+                services+=("$(basename "$sys_service")")
+                unit_types+=("service")
+                unit_scope+=("system")
+            fi
+        done
+
+        if [[ ${#provides_systemd_service[@]} -eq 0 ]]; then
+            _installation_complete
+        fi
+
+        has_socket=false
+        has_service=false
+        for type in "${unit_types[@]}"; do
+            [[ $type == "socket" ]] && has_socket=true
+            [[ $type == "service" ]] && has_service=true
+        done
+
+        if $has_socket && $has_service; then
+            unit_label="systemd ${YELLOW}services${RESET} and ${YELLOW}sockets${RESET}"
+        elif $has_socket; then
+            unit_label="systemd ${YELLOW}sockets${RESET}"
+        else
+            unit_label="systemd ${YELLOW}services${RESET}"
+        fi
+
+        printf "%s[VIBRANIUM]%s The following packages provide %s:\n" "$YELLOW" "$RESET" "$unit_label"
+        for i in "${!provides_systemd_service[@]}"; do
+            pkg="${provides_systemd_service[$i]}"
+            type="${unit_types[$i]}"
+            scope="${unit_scope[$i]}"
+
+            echo -e " - ${YELLOW}$pkg${RESET} (${scope} ${type})"
+        done
+
+        prompt2=$'\e[0;33m[VIBRANIUM]\e[0m Do you wish to enable and start them now? (Y/n): '
+        while true; do
+            printf '\e[?25h' # show cursor
+            printf "%s" "$prompt2"
+            read -r answer
+            case "$answer" in
+            [Yy][Ee][Ss] | [Yy] | "")
+                printf '\e[?25l' # Hide cursor
+                if [[ ${#user_units[@]} -gt 0 ]]; then
+                    printf "%s[VIBRANIUM]%s Enabled %s%s%s\n" "$YELLOW" "$RESET" "$YELLOW" "${user_units[@]}" "$RESET"
+                    systemctl -q --user --now enable "${user_units[@]}" &
+                fi
+
+                if [[ ${#services[@]} -gt 0 ]]; then
+                    # Since we're already in a terminal window
+                    # there is no point of using polkit window,
+                    # so use sudo
+                    printf "%s[VIBRANIUM]%s Enabled %s%s%s\n" "$YELLOW" "$RESET" "$YELLOW" "${services[@]}" "$RESET"
+                    sudo systemctl -q enable --now "${services[@]}" &
+                fi
+                break
+                ;;
+            [Nn][Oo] | [Nn])
+                printf '\e[?25l' # Hide cursor
+                break
+                ;;
+            *)                      # Wrong input
+                printf '\e[A\r\e[K' # Go up, to start, clear line
+                ;;
+            esac
+        done
+
+        _installation_complete
+        ;;
+    [Nn][Oo] | [Nn])
+        _operation_aborted
+        ;;
+    *)                      # Wrong input
+        printf '\e[A\r\e[K' # Go up, to start, clear line
+        ;;
     esac
 done
